#!/bin/bash

S=100
V=10
U=4
A=10
T=4
P=0

javac Dataflow.java
javac DataflowOrginal.java
for i in {0..10}
do
  java -Xmx2048M Dataflow $S $V $U $A $T $P >> Par.txt
  java -Xmx2048M DataflowOrginal $S $V $U $A $T $P >> Org.txt
done
diff Par.txt Org.txt
